# Generated by Django 5.2.10 on 2026-02-01 03:59

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import psqlextra.manager.manager
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_tool_profiles_and_memory_search'),
        ('memory', '0001_initial'),
    ]

    operations = [
        # Enable pgvector extension
        VectorExtension(),
        migrations.CreateModel(
            name='EmbeddingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_model', models.CharField(max_length=100)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['embedding_model', 'content_hash'], name='memory_embe_embeddi_f8c865_idx')],
                'unique_together': {('embedding_model', 'content_hash')},
            },
        ),
        migrations.CreateModel(
            name='EmbeddingChunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('message', 'Message'), ('summary', 'Summary'), ('file', 'File')], default='message', max_length=20)),
                ('source_id', models.BigIntegerField(help_text='ID of the source message, summary, or file')),
                ('text', models.TextField()),
                ('start_line', models.IntegerField(default=0)),
                ('end_line', models.IntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384, help_text='Vector embedding for similarity search')),
                ('embedding_model', models.CharField(default='all-MiniLM-L6-v2', help_text='Model used to generate embedding', max_length=100)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 hash for deduplication', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embedding_chunks', to='agents.agent')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='embedding_chunk_hnsw_idx', opclasses=['vector_cosine_ops']), models.Index(fields=['agent', 'source', 'source_id'], name='memory_embe_agent_i_8e7c34_idx'), models.Index(fields=['agent', 'content_hash'], name='memory_embe_agent_i_b09080_idx')],
            },
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
