# Generated by Django 5.2.10 on 2026-02-02 05:40

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_improve_hnsw_parameters'),
        ('memory', '0003_fix_embeddingchunk_partitioning'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='embeddingchunk',
            name='embedding_chunk_hnsw_idx',
        ),
        migrations.AddIndex(
            model_name='embeddingchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=128, fields=['embedding'], m=24, name='embedding_chunk_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
