# Generated by Django 5.2.10 on 2026-01-31 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('input_schema', models.JSONField(default=dict)),
                ('handler_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_in_groups', models.BooleanField(default=False)),
                ('require_approval', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic'), ('openai', 'Openai'), ('bedrock', 'Bedrock')], default='anthropic', max_length=20)),
                ('model_name', models.CharField(default='claude-sonnet-4-20250514', max_length=100)),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=4096)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AgentCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('encrypted_api_key', models.TextField()),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='agents.agent')),
            ],
            options={
                'verbose_name': 'Agent Credential',
                'verbose_name_plural': 'Agent Credentials',
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agents.agent')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agents.tool')),
            ],
            options={
                'unique_together': {('agent', 'tool')},
            },
        ),
    ]
