# Generated by Django 5.2.10 on 2026-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='base_url',
            field=models.URLField(blank=True, help_text='Required for Ollama/vLLM providers'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('ollama', 'Ollama'), ('vllm', 'Vllm')], default='anthropic', max_length=20),
        ),
    ]
