# Generated by Django 5.2.10 on 2026-01-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_base_url_alter_agent_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='rate_limit_enabled',
            field=models.BooleanField(default=False, help_text='Enable rate limiting for API calls'),
        ),
        migrations.AddField(
            model_name='agent',
            name='rate_limit_rpm',
            field=models.PositiveIntegerField(default=60, help_text='Maximum requests per minute (0 = unlimited)'),
        ),
    ]
