# Generated by Django 5.2.10 on 2026-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_rate_limit_enabled_agent_rate_limit_rpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='memory_search_config',
            field=models.JSONField(blank=True, default=dict, help_text='Memory search config: max_results, min_score, hybrid_weights, etc.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='memory_search_enabled',
            field=models.BooleanField(default=True, help_text='Enable memory search tool for this agent'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tool_profile',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('coding', 'Coding'), ('messaging', 'Messaging'), ('full', 'Full')], default='full', help_text='Pre-defined tool access profile', max_length=20),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools_allow',
            field=models.JSONField(blank=True, default=list, help_text='List of tool names to explicitly allow (overrides profile)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools_deny',
            field=models.JSONField(blank=True, default=list, help_text='List of tool names to explicitly deny (overrides allow)'),
        ),
    ]
