# Generated by Django 5.2.10 on 2026-02-02 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_add_tool_profiles_and_memory_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_datetime']},
        ),
    ]
